# Generated by Django 6.0.4 on 2026-06-18 19:04

import django.utils.timezone
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp')),
                ('usuario_matricula', models.CharField(blank=True, max_length=50, null=True, verbose_name='matrícula do usuário')),
                ('operacao', models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('SELECT', 'Select')], max_length=10, verbose_name='operação')),
                ('colecao', models.CharField(max_length=100, verbose_name='coleção')),
                ('documento_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID do documento')),
                ('dados_antes', models.JSONField(blank=True, null=True, verbose_name='dados antes')),
                ('dados_depois', models.JSONField(blank=True, null=True, verbose_name='dados depois')),
                ('ip_origem', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP de origem')),
                ('endpoint', models.CharField(blank=True, max_length=500, null=True, verbose_name='endpoint')),
            ],
            options={
                'verbose_name': 'log de auditoria',
                'verbose_name_plural': 'logs de auditoria',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
