# Generated by Django 6.0.4 on 2026-05-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coletor',
            name='cargo',
            field=models.CharField(blank=True, default='Agente de coleta', max_length=100, verbose_name='cargo'),
        ),
        migrations.AddField(
            model_name='coletor',
            name='zona',
            field=models.CharField(blank=True, max_length=100, verbose_name='zona'),
        ),
    ]
