# Generated by Django 6.0.5 on 2026-05-05 19:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coletor',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome', models.CharField(blank=True, max_length=150, verbose_name='nome completo')),
                ('foto_perfil', models.URLField(blank=True, verbose_name='foto de perfil')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'coletor',
                'verbose_name_plural': 'coletores',
                'ordering': ['nome'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.CharField(max_length=100, unique=True, verbose_name='ID externo')),
                ('iptu', models.CharField(max_length=20, unique=True, verbose_name='IPTU')),
                ('logradouro', models.CharField(max_length=200, verbose_name='logradouro')),
                ('numero', models.CharField(max_length=20, verbose_name='número')),
                ('bairro', models.CharField(max_length=100, verbose_name='bairro')),
                ('morador', models.CharField(max_length=150, verbose_name='morador')),
                ('elegivel', models.BooleanField(default=True, verbose_name='elegível')),
                ('sincronizado_em', models.DateTimeField(auto_now=True, verbose_name='sincronizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'imóvel',
                'verbose_name_plural': 'imóveis',
                'ordering': ['logradouro', 'numero'],
                'indexes': [models.Index(fields=['iptu'], name='api_imovel_iptu_fe733d_idx'), models.Index(fields=['elegivel'], name='api_imovel_elegive_fe9a3c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coleta_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID da coleta')),
                ('data_hora', models.DateTimeField(verbose_name='data e hora')),
                ('peso_total_kg', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='peso total (kg)')),
                ('pontos_gerados', models.IntegerField(default=0, verbose_name='pontos gerados')),
                ('foto_url', models.URLField(blank=True, verbose_name='foto')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitude')),
                ('sincronizado_core', models.BooleanField(default=False, verbose_name='sincronizado com core')),
                ('origem', models.CharField(choices=[('APP', 'App em tempo real'), ('SYNC_OFFLINE', 'Sincronização offline')], default='APP', max_length=20, verbose_name='origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('coletor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coletas', to=settings.AUTH_USER_MODEL, verbose_name='coletor')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coletas', to='api.imovel', verbose_name='imóvel')),
            ],
            options={
                'verbose_name': 'coleta',
                'verbose_name_plural': 'coletas',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='MaterialColeta',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('PAPEL', 'Papel/Papelão'), ('PLASTICO', 'Plástico'), ('VIDRO', 'Vidro'), ('METAL', 'Metal'), ('ORGANICO', 'Orgânico')], max_length=20, verbose_name='categoria')),
                ('peso_kg', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='peso (kg)')),
                ('coleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='api.coleta', verbose_name='coleta')),
            ],
            options={
                'verbose_name': 'material de coleta',
                'verbose_name_plural': 'materiais de coleta',
                'ordering': ['categoria'],
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(verbose_name='ordem')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('COLETADO', 'Coletado'), ('FALHOU', 'Falhou')], default='PENDENTE', max_length=10, verbose_name='status')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paradas', to='api.imovel', verbose_name='imóvel')),
            ],
            options={
                'verbose_name': 'parada',
                'verbose_name_plural': 'paradas',
                'ordering': ['rota', 'ordem'],
            },
        ),
        migrations.AddField(
            model_name='coleta',
            name='parada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coletas', to='api.parada', verbose_name='parada'),
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('data', models.DateField(verbose_name='data')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=20, verbose_name='status')),
                ('total_imoveis', models.IntegerField(default=0, verbose_name='total de imóveis')),
                ('imoveis_visitados', models.IntegerField(default=0, verbose_name='imóveis visitados')),
                ('coletor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to=settings.AUTH_USER_MODEL, verbose_name='coletor')),
            ],
            options={
                'verbose_name': 'rota',
                'verbose_name_plural': 'rotas',
                'ordering': ['-data', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='parada',
            name='rota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='api.rota', verbose_name='rota'),
        ),
        migrations.AddIndex(
            model_name='coleta',
            index=models.Index(fields=['coletor', 'data_hora'], name='api_coleta_coletor_5b48d4_idx'),
        ),
        migrations.AddIndex(
            model_name='coleta',
            index=models.Index(fields=['sincronizado_core'], name='api_coleta_sincron_1e252b_idx'),
        ),
        migrations.AddIndex(
            model_name='parada',
            index=models.Index(fields=['rota', 'status'], name='api_parada_rota_id_55a954_idx'),
        ),
    ]
