# Generated by Django 6.0.4 on 2026-05-12 18:48

import django_mongodb_backend.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coleta_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID da coleta')),
                ('data_hora', models.DateTimeField(verbose_name='data e hora')),
                ('peso_total_kg', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='peso total (kg)')),
                ('foto_url', models.URLField(blank=True, verbose_name='foto')),
                ('sincronizado_core', models.BooleanField(default=False, verbose_name='sincronizado com core')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'coleta',
                'verbose_name_plural': 'coletas',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.CharField(max_length=100, unique=True, verbose_name='ID externo')),
                ('iptu', models.CharField(max_length=20, unique=True, verbose_name='IPTU')),
                ('logradouro', models.CharField(max_length=200, verbose_name='logradouro')),
                ('numero', models.CharField(max_length=20, verbose_name='número')),
                ('bairro', models.CharField(max_length=100, verbose_name='bairro')),
                ('morador', models.CharField(max_length=150, verbose_name='morador')),
                ('elegivel', models.BooleanField(default=True, verbose_name='elegível')),
                ('sincronizado_em', models.DateTimeField(auto_now=True, verbose_name='sincronizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'imóvel',
                'verbose_name_plural': 'imóveis',
                'ordering': ['logradouro', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('data', models.DateField(verbose_name='data')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=20, verbose_name='status')),
                ('total_imoveis', models.IntegerField(default=0, verbose_name='total de imóveis')),
                ('imoveis_visitados', models.IntegerField(default=0, verbose_name='imóveis visitados')),
            ],
            options={
                'verbose_name': 'rota',
                'verbose_name_plural': 'rotas',
                'ordering': ['-data', 'nome'],
            },
        ),
    ]
