# Generated by Django 6.0.4 on 2026-05-19 02:17

import django.db.models.deletion
import django_mongodb_backend.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.CharField(max_length=100, unique=True, verbose_name='ID externo')),
                ('iptu', models.CharField(max_length=20, unique=True, verbose_name='IPTU')),
                ('logradouro', models.CharField(max_length=200, verbose_name='logradouro')),
                ('numero', models.CharField(max_length=20, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='bairro')),
                ('morador', models.CharField(max_length=150, verbose_name='morador')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('elegivel', models.BooleanField(default=True, verbose_name='elegível')),
                ('motivo_inelegivel', models.TextField(blank=True, verbose_name='motivo inelegível')),
                ('sincronizado_em', models.DateTimeField(auto_now=True, verbose_name='sincronizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'imóvel',
                'verbose_name_plural': 'imóveis',
                'ordering': ['logradouro', 'numero'],
                'indexes': [models.Index(fields=['iptu'], name='coleta_imov_iptu_e98ea2_idx'), models.Index(fields=['elegivel'], name='coleta_imov_elegive_22f1fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coleta_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID da coleta')),
                ('offline_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='ID offline')),
                ('codigo', models.CharField(blank=True, max_length=20, verbose_name='código')),
                ('data_hora', models.DateTimeField(verbose_name='data e hora')),
                ('peso_total_kg', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='peso total (kg)')),
                ('pontos_gerados', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='pontos gerados')),
                ('foto_url', models.URLField(blank=True, verbose_name='foto')),
                ('gps_latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('gps_longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('status', models.CharField(choices=[('confirmada', 'Confirmada'), ('pendente', 'Pendente'), ('erro', 'Erro')], default='confirmada', max_length=20, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('sincronizado_core', models.BooleanField(default=False, verbose_name='sincronizado com core')),
                ('tentativas_sincronizacao', models.IntegerField(default=0, verbose_name='tentativas de sincronização')),
                ('erro_ultima_tentativa', models.TextField(blank=True, verbose_name='erro última tentativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('coletor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coletas', to=settings.AUTH_USER_MODEL, verbose_name='coletor')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coletas', to='coleta.imovel', verbose_name='imóvel')),
            ],
            options={
                'verbose_name': 'coleta',
                'verbose_name_plural': 'coletas',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='MaterialColeta',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('plastico', 'Plástico'), ('papel', 'Papel'), ('vidro', 'Vidro'), ('metal', 'Metal'), ('organico', 'Orgânico')], max_length=20, verbose_name='tipo')),
                ('peso_kg', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='peso (kg)')),
                ('coleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='coleta.coleta', verbose_name='coleta')),
            ],
            options={
                'verbose_name': 'material da coleta',
                'verbose_name_plural': 'materiais da coleta',
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, verbose_name='código')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('zona', models.CharField(blank=True, max_length=100, verbose_name='zona')),
                ('data', models.DateField(verbose_name='data')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=20, verbose_name='status')),
                ('total_imoveis', models.IntegerField(default=0, verbose_name='total de imóveis')),
                ('imoveis_visitados', models.IntegerField(default=0, verbose_name='imóveis visitados')),
                ('hora_prevista_encerro', models.TimeField(blank=True, null=True, verbose_name='hora prevista de encerro')),
                ('coletor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to=settings.AUTH_USER_MODEL, verbose_name='coletor')),
            ],
            options={
                'verbose_name': 'rota',
                'verbose_name_plural': 'rotas',
                'ordering': ['-data', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='RotaImovel',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.IntegerField(default=0, verbose_name='sequência')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('coletado', 'Coletado'), ('recusado', 'Recusado')], default='pendente', max_length=20, verbose_name='status')),
                ('distancia_metros', models.FloatField(blank=True, null=True, verbose_name='distância (metros)')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paradas', to='coleta.imovel', verbose_name='imóvel')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='coleta.rota', verbose_name='rota')),
            ],
            options={
                'verbose_name': 'parada',
                'verbose_name_plural': 'paradas',
                'ordering': ['sequencia'],
            },
        ),
        migrations.AddIndex(
            model_name='coleta',
            index=models.Index(fields=['coletor', 'data_hora'], name='coleta_cole_coletor_064195_idx'),
        ),
        migrations.AddIndex(
            model_name='coleta',
            index=models.Index(fields=['sincronizado_core'], name='coleta_cole_sincron_48d35c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rotaimovel',
            unique_together={('rota', 'imovel')},
        ),
    ]
