# Generated by Django 6.0.4 on 2026-05-12 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coleta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coleta',
            name='coletor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coletas', to=settings.AUTH_USER_MODEL, verbose_name='coletor'),
        ),
        migrations.AddIndex(
            model_name='imovel',
            index=models.Index(fields=['iptu'], name='coleta_imov_iptu_e98ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='imovel',
            index=models.Index(fields=['elegivel'], name='coleta_imov_elegive_22f1fb_idx'),
        ),
        migrations.AddField(
            model_name='coleta',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coletas', to='coleta.imovel', verbose_name='imóvel'),
        ),
        migrations.AddField(
            model_name='rota',
            name='coletor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to=settings.AUTH_USER_MODEL, verbose_name='coletor'),
        ),
        migrations.AddIndex(
            model_name='coleta',
            index=models.Index(fields=['coletor', 'data_hora'], name='coleta_cole_coletor_064195_idx'),
        ),
        migrations.AddIndex(
            model_name='coleta',
            index=models.Index(fields=['sincronizado_core'], name='coleta_cole_sincron_48d35c_idx'),
        ),
    ]
