# Generated by Django 6.0.4 on 2026-05-13 12:32

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleta',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, verbose_name='código'),
        ),
        migrations.AddField(
            model_name='coleta',
            name='erro_ultima_tentativa',
            field=models.TextField(blank=True, verbose_name='erro última tentativa'),
        ),
        migrations.AddField(
            model_name='coleta',
            name='gps_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='coleta',
            name='gps_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='coleta',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AddField(
            model_name='coleta',
            name='offline_id',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='ID offline'),
        ),
        migrations.AddField(
            model_name='coleta',
            name='pontos_gerados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='pontos gerados'),
        ),
        migrations.AddField(
            model_name='coleta',
            name='status',
            field=models.CharField(choices=[('confirmada', 'Confirmada'), ('pendente', 'Pendente'), ('erro', 'Erro')], default='confirmada', max_length=20, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='coleta',
            name='tentativas_sincronizacao',
            field=models.IntegerField(default=0, verbose_name='tentativas de sincronização'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='motivo_inelegivel',
            field=models.TextField(blank=True, verbose_name='motivo inelegível'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefone'),
        ),
        migrations.AddField(
            model_name='rota',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, verbose_name='código'),
        ),
        migrations.AddField(
            model_name='rota',
            name='hora_prevista_encerro',
            field=models.TimeField(blank=True, null=True, verbose_name='hora prevista de encerro'),
        ),
        migrations.AddField(
            model_name='rota',
            name='zona',
            field=models.CharField(blank=True, max_length=100, verbose_name='zona'),
        ),
        migrations.CreateModel(
            name='MaterialColeta',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('plastico', 'Plástico'), ('papel', 'Papel'), ('vidro', 'Vidro'), ('metal', 'Metal'), ('organico', 'Orgânico')], max_length=20, verbose_name='tipo')),
                ('peso_kg', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='peso (kg)')),
                ('coleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='coleta.coleta', verbose_name='coleta')),
            ],
            options={
                'verbose_name': 'material da coleta',
                'verbose_name_plural': 'materiais da coleta',
            },
        ),
        migrations.CreateModel(
            name='RotaImovel',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.IntegerField(default=0, verbose_name='sequência')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('coletado', 'Coletado'), ('recusado', 'Recusado')], default='pendente', max_length=20, verbose_name='status')),
                ('distancia_metros', models.FloatField(blank=True, null=True, verbose_name='distância (metros)')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paradas', to='coleta.imovel', verbose_name='imóvel')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='coleta.rota', verbose_name='rota')),
            ],
            options={
                'verbose_name': 'parada',
                'verbose_name_plural': 'paradas',
                'ordering': ['sequencia'],
                'unique_together': {('rota', 'imovel')},
            },
        ),
    ]
