# Generated by Django 6.0.4 on 2026-06-07 19:15

from django.db import migrations, models
from pymongo import GEOSPHERE
from pymongo.operations import IndexModel

# Mesma convenção de nome usada pelo índice espacial do django-mongodb-backend:
# "<db_table>_<column>_id".
INDICE_2DSPHERE = 'coleta_imovel_location_id'


def criar_indice_2dsphere(apps, schema_editor):
    """Cria o índice geoespacial 2dsphere sobre o campo location."""
    colecao = schema_editor.connection.get_collection('coleta_imovel')
    colecao.create_indexes(
        [IndexModel([('location', GEOSPHERE)], name=INDICE_2DSPHERE)]
    )


def remover_indice_2dsphere(apps, schema_editor):
    colecao = schema_editor.connection.get_collection('coleta_imovel')
    colecao.drop_index(INDICE_2DSPHERE)


def preencher_location(apps, schema_editor):
    """Preenche location dos imóveis já salvos a partir de latitude/longitude."""
    Imovel = apps.get_model('coleta', 'Imovel')
    for imovel in Imovel.objects.filter(latitude__isnull=False, longitude__isnull=False):
        imovel.location = {
            'type': 'Point',
            'coordinates': [float(imovel.longitude), float(imovel.latitude)],
        }
        imovel.save(update_fields=['location'])


def limpar_location(apps, schema_editor):
    Imovel = apps.get_model('coleta', 'Imovel')
    Imovel.objects.filter(location__isnull=False).update(location=None)


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0006_imovel_latitude_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='location',
            field=models.JSONField(blank=True, null=True, verbose_name='localização (GeoJSON)'),
        ),
        migrations.RunPython(criar_indice_2dsphere, remover_indice_2dsphere),
        migrations.RunPython(preencher_location, limpar_location),
    ]
