# Generated by Django 6.0.4 on 2026-06-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0007_imovel_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='longitude',
        ),
    ]
