# Generated by Django 6.0.4 on 2026-07-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0009_imovel_proprietario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='num_moradores',
            field=models.IntegerField(default=1, verbose_name='número de moradores'),
        ),
    ]
