# Generated by Django 6.0.4 on 2026-07-13 00:08

import django_mongodb_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0011_imovel_location_2dsphere_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventoauditoria',
            new_name='evento_audi_timesta_6d539e_idx',
            old_name='evento_auditoria_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='eventoauditoria',
            new_name='evento_audi_origem_d50148_idx',
            old_name='evento_auditoria_origem_idx',
        ),
        migrations.RenameIndex(
            model_name='eventoauditoria',
            new_name='evento_audi_coletor_ab3de1_idx',
            old_name='evento_auditoria_coletor_idx',
        ),
        migrations.AlterField(
            model_name='eventoauditoria',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
